[package]
name = "livesplit-core"
version = "0.11.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
documentation = "https://docs.rs/livesplit-core/"
repository = "https://github.com/LiveSplit/livesplit-core"
license = "Apache-2.0/MIT"
description = "livesplit-core is a library that provides a lot of functionality for creating a speedrun timer."
readme = "README.md"
keywords = ["speedrun", "timer", "livesplit"]
include = [
    "/benches/*",
    "/src/*",
    "/Cargo.toml",
    "/CHANGELOG.md",
    "/CODE_OF_CONDUCT.md",
    "/LICENSE-APACHE",
    "/LICENSE-MIT",
    "/README.md"
]
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[badges]
travis-ci = { repository = "LiveSplit/livesplit-core" }
appveyor = { repository = "CryZe/livesplit-core" }

[profile.release]
lto = true
panic = "abort"

[workspace]
members = ["capi", "capi/bind_gen", "capi/js", "capi/staticlib", "capi/cdylib", "crates/*"]

[dependencies]
cfg-if = "0.1.7"
base64 = { version = "0.10.0", optional = true } # Not no_std, but there is a PR https://github.com/marshallpierce/rust-base64/pull/62
byteorder = { version = "1.3.2", optional = true } # Not no_std, because of io
chrono = { version = "0.4.0", features = ["serde", "clock"], default-features = false, optional = true } # Not no_std, but we probably wouldn't use it there anyway.
derive_more = { version = "0.15.0", features = ["no_std"] } # Has a "no_std" feature. Urgh
image = { version = "0.22.0", features = ["png_codec"], default-features = false, optional = true } # Not no_std, too much io.
indexmap = { version = "1.0.1", default-features = false, features = ["serde-1"], optional = true } # Not no_std, but there is a PR https://github.com/bluss/indexmap/pull/92
livesplit-hotkey = { path = "crates/livesplit-hotkey", version = "0.5.0", optional = true } # Not no_std, but we don't even need this on no_std.
odds = { version = "0.3.1", default-features = false } # Yes there is a "std" feature. We don't even use it.
ordered-float = { version = "1.0.0", default-features = false } # Yes, there is a "std" feature. We don't even use it.
palette = { git = "https://github.com/CryZe/palette", branch = "no-std", default-features = false } # Yes, there is a "std" feature. We don't even use it. But it is unreleased. Temporary fork to fix a bug.
parking_lot = { version = "0.9.0", default-features = false, optional = true } # No idea tbh, but we probably don't even need parking_lot on no_std
quick-xml = { version = "0.15.0", default-features = false, optional = true } # Not no_std, because of io
serde = { version = "1.0.98", features = ["derive", "alloc"], default-features = false } # Yes, there is a "std" feature. We don't even use it.
serde_json = { version = "1.0.8", optional = true } # Not no_std, because of io, but there is a PR https://github.com/serde-rs/json/pull/516
snafu = { git = "https://github.com/CryZe/snafu", branch = "no-std", default-features = false, features = ["rust_1_30"] } # Not no_std, because of std::error::Error, but could be a trivial PR to do everything but std:error::Error on no_std
unicase = { git = "https://github.com/CryZe/unicase", branch = "no-std", default-features = false } # Temporary fork
utf-8 = { version = "0.7.4", optional = true } # Not no_std, because of io
hashbrown = { git = "https://github.com/rust-lang/hashbrown", default-features = false }
libm = "0.1.4"

# Rendering
euclid = { git = "https://github.com/CryZe/euclid", branch = "actual-no-std", default-features = false, optional = true } # Is blocked by num-traits, which has a PR here: https://github.com/rust-num/num-traits/pull/99
livesplit-title-abbreviations = { path = "crates/livesplit-title-abbreviations", version = "0.1.0", optional = true }
lyon_path = { git = "https://github.com/CryZe/lyon", branch = "no-std", default-features = false, optional = true }
lyon_tessellation = { git = "https://github.com/CryZe/lyon", branch = "no-std", default-features = false, optional = true }
rusttype = { git = "https://github.com/CryZe/rusttype", branch = "no-std", default-features = false, optional = true }
smallvec = { git = "https://github.com/CryZe/rust-smallvec", branch = "no-std", default-features = false, optional = true } # They only have nightly alloc support.

# Software Rendering
euc = { version = "0.3.0", default-features = false, optional = true }
vek = { version = "0.9.8", default-features = false, optional = true }

[dev-dependencies]
# Urgh more dev-dependency leaking
# memmem = "0.1.1"
# criterion = "0.2.5"
# crc = "1.8.1"

[features]
# default = ["image-shrinking", "std"]
default = ["rendering"]
# TODO: Double Check that std properly communicates the std feature through the dependency graph
std = ["base64", "byteorder", "chrono", "image", "indexmap", "livesplit-hotkey", "parking_lot", "quick-xml", "serde_json", "utf-8", "snafu/std"]
more-image-formats = ["image/webp", "image/pnm", "image/ico", "image/jpeg", "image/gif_codec", "image/tiff", "image/tga", "image/bmp", "image/hdr"]
image-shrinking = ["more-image-formats"]
# rendering = ["more-image-formats", "euclid", "livesplit-title-abbreviations",
# "lyon", "rusttype", "smallvec"]
rendering = ["euclid", "livesplit-title-abbreviations", "lyon_path", "lyon_tessellation", "rusttype", "smallvec"]
software-rendering = ["rendering", "euc", "vek"]

[[bench]]
name = "balanced_pb"
harness = false

[[bench]]
name = "parsing"
harness = false

[[bench]]
name = "software_rendering"
harness = false
