[package]
name = "capi"
version = "0.8.1"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[dependencies]
livesplit-core = { path = ".." }
serde_json = "1.0.8"

[lib]
name = "livesplit_core"
crate-type = ["cdylib", "staticlib"]
